CREATE PROCEDURE DAY_SERV_MAP
	   (@HOS_CD nvarchar,
		@DAY_CLINIC_CD nvarchar,    	          
		@SERV_TYP_CD nvarchar,     	            
		@SERV_CD nvarchar,     	            
		@SUN_AVL_FLG char='N',    	
		@MON_AVL_FLG char='N',   
		@TUE_AVL_FLG char='N',    	
		@WED_AVL_FLG char='N',    	
		@THU_AVL_FLG char='N',    	
		@FRI_AVL_FLG char='N',   	
		@SAT_AVL_FLG char='N',    	
		@SUN_FR_TM nvarchar,
		@SUN_TO_TM nvarchar, 
		@MON_FR_TM nvarchar, 
		@MON_TO_TM nvarchar, 
		@TUE_FR_TM nvarchar,
		@TUE_TO_TM nvarchar,
		@WED_FR_TM nvarchar,
		@WED_TO_TM nvarchar,     	               	      
		@THU_FR_TM nvarchar,     	               	     
		@THU_TO_TM nvarchar,     	               	     
		@FRI_FR_TM nvarchar,     	               	      
		@FRI_TO_TM nvarchar,     	               	      
		@SAT_FR_TM nvarchar,     	               	     
		@SAT_TO_TM nvarchar,    	               	     
		@SUN_SERV_MAX_NO int,
		@MON_SERV_MAX_NO int,	
		@TUE_SERV_MAX_NO int,	
		@WED_SERV_MAX_NO int,	
		@THU_SERV_MAX_NO int,	
		@FRI_SERV_MAX_NO int,	
		@SAT_SERV_MAX_NO int,	
		@ENTRY_DT Date ='1/1/1990',
		@USER_CD nvarchar,
		@SESSION_ID int,	
		@MOD_ID Date='1/1/1990',
		@SUB_MOD_ID nvarchar,
		@ACT_FLG char='A',
		@MOD_DT Date='1/1/1990', 
		@QueryType nvarchar(10) = 'Insert')
	AS
	BEGIN
		SET NOCOUNT ON;
		IF @QueryType = 'Insert'
		BEGIN 
		INSERT INTO [dbo].[DAY_SERV_MAP]
			   ([HOS_CD],
				[DAY_CLINIC_CD],    	          
				[SERV_TYP_CD],     	            
				[SERV_CD],     	            
				[SUN_AVL_FLG],    	
				[MON_AVL_FLG],   
				[TUE_AVL_FLG],    	
				[WED_AVL_FLG],    	
				[THU_AVL_FLG],    	
				[FRI_AVL_FLG],   	
				[SAT_AVL_FLG],    	
				[SUN_FR_TM],
				[SUN_TO_TM], 
				[MON_FR_TM], 
				[MON_TO_TM], 
				[TUE_FR_TM],
				[TUE_TO_TM],
				[WED_FR_TM],
				[WED_TO_TM],     	               	      
				[THU_FR_TM],     	               	     
				[THU_TO_TM],     	               	     
				[FRI_FR_TM],     	               	      
				[FRI_TO_TM],     	               	      
				[SAT_FR_TM],     	               	     
				[SAT_TO_TM],    	               	     
				[SUN_SERV_MAX_NO],
				[MON_SERV_MAX_NO],	
				[TUE_SERV_MAX_NO],	
				[WED_SERV_MAX_NO],	
				[THU_SERV_MAX_NO],	
				[FRI_SERV_MAX_NO],	
				[SAT_SERV_MAX_NO],	
				[ENTRY_DT],
				[USER_CD],
				[SESSION_ID],	
				[MOD_ID],
				[SUB_MOD_ID],
				[ACT_FLG],
				[MOD_DT]
			   )
		VALUES
		  (@HOS_CD,
			@DAY_CLINIC_CD,    	          
			@SERV_TYP_CD,     	            
			@SERV_CD,     	            
			@SUN_AVL_FLG,    	
			@MON_AVL_FLG,   
			@TUE_AVL_FLG,    	
			@WED_AVL_FLG,    	
			@THU_AVL_FLG,    	
			@FRI_AVL_FLG,   	
			@SAT_AVL_FLG,    	
			@SUN_FR_TM,
			@SUN_TO_TM, 
			@MON_FR_TM, 
			@MON_TO_TM, 
			@TUE_FR_TM,
			@TUE_TO_TM,
			@WED_FR_TM,
			@WED_TO_TM,     	               	      
			@THU_FR_TM,     	               	     
			@THU_TO_TM,     	               	     
			@FRI_FR_TM,     	               	      
			@FRI_TO_TM,     	               	      
			@SAT_FR_TM,     	               	     
			@SAT_TO_TM,    	               	     
			@SUN_SERV_MAX_NO,
			@MON_SERV_MAX_NO,	
			@TUE_SERV_MAX_NO,	
			@WED_SERV_MAX_NO,	
			@THU_SERV_MAX_NO,	
			@FRI_SERV_MAX_NO,	
			@SAT_SERV_MAX_NO,	
			@ENTRY_DT,
			@USER_CD,
			@SESSION_ID,	
			@MOD_ID,
			@SUB_MOD_ID,
			@ACT_FLG,
			@MOD_DT
			);
	  IF @@ROWCOUNT = 1
		RETURN 1;
	  ELSE
		RETURN 0;
	END

	ELSE IF @QueryType = 'Update'
		BEGIN 
			UPDATE DAY_SERV_MAP
				SET [SERV_TYP_CD] = @SERV_TYP_CD, 
				[SERV_CD] = @SERV_CD, 
				[SUN_AVL_FLG] = @SUN_AVL_FLG, 
				[MON_AVL_FLG] = @MON_AVL_FLG, 
				[TUE_AVL_FLG] = @TUE_AVL_FLG, 
				[WED_AVL_FLG] = @WED_AVL_FLG, 
				[THU_AVL_FLG] = @THU_AVL_FLG, 
				[FRI_AVL_FLG] = @FRI_AVL_FLG, 
				[SAT_AVL_FLG] = @SAT_AVL_FLG, 
				[SUN_FR_TM] = @SUN_FR_TM, 
				[SUN_TO_TM] = @SUN_TO_TM, 
				[MON_FR_TM] = @MON_FR_TM, 
				[MON_TO_TM] = @MON_TO_TM, 
				[TUE_FR_TM] = @TUE_FR_TM, 
				[TUE_TO_TM] = @TUE_TO_TM, 
				[WED_FR_TM] = @WED_FR_TM, 
				[WED_TO_TM] = @WED_TO_TM, 
				[THU_FR_TM] = @THU_FR_TM, 
				[THU_TO_TM] = @THU_TO_TM, 
				[FRI_FR_TM] = @FRI_FR_TM, 
				[FRI_TO_TM] = @FRI_TO_TM, 
				[SAT_FR_TM] = @SAT_FR_TM, 
				[SAT_TO_TM] = @SAT_TO_TM, 
				[SUN_SERV_MAX_NO] = @SUN_SERV_MAX_NO, 
				[MON_SERV_MAX_NO] = @MON_SERV_MAX_NO, 
				[TUE_SERV_MAX_NO] = @TUE_SERV_MAX_NO, 
				[WED_SERV_MAX_NO] = @WED_SERV_MAX_NO, 
				[THU_SERV_MAX_NO] = @THU_SERV_MAX_NO, 
				[FRI_SERV_MAX_NO] = @FRI_SERV_MAX_NO, 
				[SAT_SERV_MAX_NO] = @SAT_SERV_MAX_NO, 
				[ENTRY_DT] = @ENTRY_DT, 
				[USER_CD] = @USER_CD, 
				[SESSION_ID] = @SESSION_ID, 
				[MOD_ID] = @MOD_ID, 
				[SUB_MOD_ID] = @SUB_MOD_ID, 
				[ACT_FLG] = @ACT_FLG, 
				[MOD_DT] = @MOD_DT
		 WHERE [HOS_CD] = @HOS_CD AND [DAY_CLINIC_CD] = @DAY_CLINIC_CD
		 END
ELSE IF @QueryType = 'Delete'
BEGIN
		DELETE FROM [dbo].[DAY_SERV_MAP]
		WHERE [HOS_CD] = @HOS_CD AND [DAY_CLINIC_CD] = @DAY_CLINIC_CD
		END
END