Create Table DAY_DLY_RST(
HOS_CD varchar(10) Not Null  ,	
DAY_CLINIC_CD varchar(10) Not Null  ,	
RST_DT Date Not Null  ,
RST_NO varchar(10) Not Null  ,	
UNIT_DEPD_FLG char(1) Default 'N' Not Null  ,
FROM_TM char(5) Not Null,
TO_TM varchar(5) Not Null,	
VENUE_NM varchar(50),	
PH_ANC_FLG char(1) Default 'N'	Not Null  ,	
PH_DLV_FLG char(1) Default 'N' Not Null  ,	
PH_PNC_FLG char(1) Default 'N' Not Null  ,
PH_VAC_FLG char(1) Default 'N' Not Null  ,	
PH_RNTCP_FLG char(1) Default 'N' Not Null  ,	
PH_NLEP_FLG char(1) Default 'N'	Not Null  ,	    	
ACTIVE_FLG char(1)	Default 'Y'	Not Null  ,	
ENTRY_DT Date Not Null  ,	
USER_CD varchar(10) Not Null  ,	
SESSION_ID Numeric(9) Not Null  ,	
MOD_ID varchar(2) Not Null  ,
SUB_MOD_ID varchar(3) Not Null  ,	
ACT_FLG char(1) Default 'A' Not Null,	
MOD_DT Date,	
Constraint PK001_M0390_0008 Primary Key  (HOS_CD,DAY_CLINIC_CD,RST_DT,RST_NO),
Constraint FK001_M0390_0008 Foreign Key  (HOS_CD,DAY_CLINIC_CD) References DAY_CLINIC_MST(HOS_CD,DAY_CLINIC_CD) ,
Constraint CK009_M0390_0008 Check (ACTIVE_FLG in ('Y','N')),
Constraint CK001_M0390_0008 Check (ACT_FLG in ('A','I','D')),
Constraint CK002_M0390_0008 Check (UNIT_DEPD_FLG in ('Y','N')),
Constraint CK003_M0390_0008 Check (PH_ANC_FLG in ('Y','N')),
Constraint CK004_M0390_0008 Check (PH_DLV_FLG in ('Y','N')),
Constraint CK005_M0390_0008 Check (PH_PNC_FLG in ('Y','N')),
Constraint CK006_M0390_0008 Check (PH_VAC_FLG in ('Y','N')),
Constraint CK007_M0390_0008 Check (PH_RNTCP_FLG in ('Y','N')),
Constraint CK008_M0390_0008 Check (PH_NLEP_FLG in('Y','N'))
); 
