Create Table DAY_DOC_MST(
HOS_CD varchar(10) Not Null  ,	
DOC_CD varchar(10) Not Null  ,	
DOC_NM varchar(50) Not Null  ,	
ADDRESS varchar(100),
SEX char(1) Default 'M' Not Null  ,
SPL_CD varchar(10) Not Null  ,
RES_PH varchar(12),	
CHAMBER_PH varchar(12),	
MOBILE_NO varchar(15),
EMAIL_ID varchar(20),
REGI_NO varchar(25),
GRADE_FLG char(1) Default 'S' Not Null,	
HOS_DOC_FLG char(1) Default 'N' Not Null,
REF_DOC_CD varchar(10),
ACTIVE_FLG char(1) Default 'Y' Not Null,	
REMARKS varchar(100),	
PRL_EMP_CD varchar(22),
ENTRY_DT Date,	
USER_CD varchar(10),	
SESSION_ID numeric(9),	
ACT_FLG char(1) Default 'A' Not Null,	                                                                      
MOD_DT Date,     	               	          	
SESSION_ID_WEB varchar(30) Not Null,	
  
Constraint PK001_M0236_0021 Primary Key (HOS_CD,DOC_CD),
Constraint CK003_M0236_0021 Check (ACT_FLG in ('A','I','D')),
Constraint CK001_M0236_0021 Check (ACTIVE_FLG in ('Y','N')),
Constraint CK002_M0236_0021 Check (SEX in ('M','F'))
); 
