Create Table DAY_CLINIC_MST(
HOS_CD                   	nvarchar(10)    	               	Not Null  ,
DAY_CLINIC_CD            	nvarchar(10)    	               	Not Null  ,
DAY_CLINIC_NM            	nvarchar(100)   	               	Not Null  ,
DAY_CLINIC_TYP_CD        	nvarchar(5)     	               	Not Null  ,
UNIT_DEPD_FLG            	nvarchar(1)     	Default 'N'    	Not Null  ,
MON_FLG                  	nvarchar(1)     	Default 'N'    	Not Null  ,	
TUE_FLG                  	nvarchar(1)     	Default 'N'    	Not Null  ,
WED_FLG                  	nvarchar(1)     	Default 'N'    	Not Null  ,
THU_FLG                  	nvarchar(1)     	Default 'N'    	Not Null  ,
FRI_FLG                  	nvarchar(1)     	Default 'N'    	Not Null  ,
SAT_FLG                  	nvarchar(1)     	Default 'N'    	Not Null  ,	
SUN_FLG                  	nvarchar(1)     	Default 'N'    	Not Null  ,	
MON_FR_TM                	nvarchar(5),	
MON_TO_TM                	nvarchar(5),	
TUE_FR_TM                	nvarchar(5),	
TUE_TO_TM                	nvarchar(5),
WED_FR_TM                	nvarchar(5),	
WED_TO_TM                	nvarchar(5),	
THU_FR_TM                	nvarchar(5),
THU_TO_TM                	nvarchar(5),	
FRI_FR_TM                	nvarchar(5),	
FRI_TO_TM                	nvarchar(5),	
SAT_FR_TM                	nvarchar(5),	
SAT_TO_TM                	nvarchar(5),	
SUN_FR_TM                	nvarchar(5),	
SUN_TO_TM                	nvarchar(5),	
MON_VENUE_NM             	nvarchar(50),	
TUE_VENUE_NM             	nvarchar(50),	
WED_VENUE_NM             	nvarchar(50),	
THU_VENUE_NM             	nvarchar(50),	
FRI_VENUE_NM             	nvarchar(50),	
SAT_VENUE_NM             	nvarchar(50),	
SUN_VENUE_NM             	nvarchar(50),	
PH_ANC_FLG               	char(1)     	Default 'N'    	Not Null  ,	
PH_DLV_FLG               	char(1)     	Default 'N'    	Not Null  ,	
PH_PNC_FLG               	char(1)     	Default 'N'    	Not Null  ,	
PH_VAC_FLG               	char(1)     	Default 'N'    	Not Null  ,	
PH_RNTCP_FLG             	char(1)     	Default 'N'    	Not Null  ,	
PH_NLEP_FLG              	char(1)     	Default 'N'    	Not Null  ,	
BASE_LVL_REF_CD          	nvarchar(6)     	               	Not Null  ,	
LVL_REF_CD               	nvarchar(6) Not Null  ,	
ACTIVE_FLG               	char(1)     	Default 'Y'    	Not Null  ,	
ENTRY_DT                 	date Not Null  ,
USER_CD                  	nvarchar(10) Not Null  ,
SESSION_ID               	Numeric(9) Not Null  ,
MOD_ID                   	nvarchar(2) Not Null,
SUB_MOD_ID               	nvarchar(3) Not Null,
ACT_FLG                  	char(1)     	Default 'A'    	Not Null,	
MOD_DT                   	date,	
SESSION_ID_WEB           	nvarchar(30),
  
Constraint PK001_M0389_0001 Primary Key  (HOS_CD,DAY_CLINIC_CD),
Constraint FK001_M0389_0001 Foreign Key  (DAY_CLINIC_TYP_CD) References DAY_CLINIC_TYP_MST (DAY_CLINIC_TYP_CD) ,
Constraint FK002_M0389_0001 Foreign Key (BASE_LVL_REF_CD,LVL_REF_CD) References MDT_LOC_LVL_REF_MST (BASE_LVL_REF_CD,LVL_REF_CD),
 
Constraint CK001_M0389_0001 Check (SUN_FLG in ('Y','N')),
Constraint CK002_M0389_0001 Check (FRI_FLG in ('Y','N')),
Constraint CK003_M0389_0001 Check (SAT_FLG in ('Y','N')),
Constraint CK004_M0389_0001 Check (MON_FLG in ('Y','N')),
Constraint CK005_M0389_0001 Check (TUE_FLG in ('Y','N')),
Constraint CK006_M0389_0001 Check (WED_FLG in ('Y','N')),
Constraint CK007_M0389_0001 Check (THU_FLG in ('Y','N')),
Constraint CK008_M0389_0001 Check (ACTIVE_FLG in ('Y','N')),
Constraint CK009_M0389_0001 Check (PH_RNTCP_FLG in ('Y','N')),
Constraint CK010_M0389_0001 Check (PH_NLEP_FLG in ('Y','N')),
Constraint CK011_M0389_0001 Check (PH_ANC_FLG in ('Y','N')),
Constraint CK012_M0389_0001 Check (PH_DLV_FLG in ('Y','N')),
Constraint CK013_M0389_0001 Check (PH_PNC_FLG in ('Y','N')),
Constraint CK014_M0389_0001 Check (PH_VAC_FLG in ('Y','N')),
Constraint CK015_M0389_0001 Check (UNIT_DEPD_FLG in ('Y','N')),
Constraint CK016_M0389_0001 Check (ACT_FLG in ('A','I','D'))
); 
