Create Table DAY_SERV_MAP(
HOS_CD nvarchar(10) Not Null  ,	
DAY_CLINIC_CD nvarchar(10) Not Null  ,	
SERV_TYP_CD nvarchar(5) Not Null  ,	
SERV_CD nvarchar(7) Not Null  ,	
SUN_AVL_FLG char(1) Default 'N' Not Null  ,	
MON_AVL_FLG char(1) Default 'N' Not Null  ,	
TUE_AVL_FLG char(1) Default 'N' Not Null  ,	
WED_AVL_FLG char(1)	Default 'N' Not Null  ,	
THU_AVL_FLG char(1)	Default 'N' Not Null  ,	
FRI_AVL_FLG char(1)	Default 'N' Not Null  ,	
SAT_AVL_FLG char(1)	Default 'N' Not Null  ,	
SUN_FR_TM nvarchar(5),	
SUN_TO_TM nvarchar(5),	
MON_FR_TM nvarchar(5),
MON_TO_TM nvarchar(5),	
TUE_FR_TM nvarchar(5),	
TUE_TO_TM nvarchar(5),	
WED_FR_TM nvarchar(5),	
WED_TO_TM nvarchar(5),	
THU_FR_TM nvarchar(5),	
THU_TO_TM nvarchar(5),
FRI_FR_TM nvarchar(5),	
FRI_TO_TM nvarchar(5),	
SAT_FR_TM nvarchar(5),	
SAT_TO_TM nvarchar(5),
SUN_SERV_MAX_NO Numeric(9) Default 0 Not Null  , 
MON_SERV_MAX_NO Numeric(9) Default 0 Not Null  ,
TUE_SERV_MAX_NO Numeric(9) Default 0 Not Null  ,	
WED_SERV_MAX_NO Numeric(9) Default 0 Not Null,	
THU_SERV_MAX_NO Numeric(9) Default 0 Not Null,	
FRI_SERV_MAX_NO Numeric(9) Default 0  Not Null  ,
SAT_SERV_MAX_NO Numeric(9) Default 0  Not Null  ,	
ENTRY_DT Date Not Null,
USER_CD nvarchar(10) Not Null,
SESSION_ID Numeric(9)	Not Null,	
MOD_ID nvarchar(2) Not Null,	
SUB_MOD_ID nvarchar(3) Not Null,	
ACT_FLG char(1) Default 'A' Not Null  ,                                                                           	
MOD_DT Date,	
  
Constraint PK001_M0390_0007 Primary Key (HOS_CD,DAY_CLINIC_CD,SERV_TYP_CD,SERV_CD),
Constraint FK001_M0390_0007 Foreign Key (SERV_TYP_CD,SERV_CD) References DAY_SERV_MST(SERV_TYP_CD,SERV_CD) ,
Constraint FK002_M0390_0007 Foreign Key (HOS_CD,DAY_CLINIC_CD) References DAY_CLINIC_MST(HOS_CD,DAY_CLINIC_CD) ,
Constraint CK001_M0390_0007 Check (WED_AVL_FLG in ('Y','N')),
Constraint CK002_M0390_0007 Check (MON_AVL_FLG in ('Y','N')),
Constraint CK003_M0390_0007 Check (TUE_AVL_FLG in ('Y','N')),
Constraint CK004_M0390_0007 Check (SAT_AVL_FLG in ('Y','N')),
Constraint CK005_M0390_0007 Check (THU_AVL_FLG in ('Y','N')),
Constraint CK006_M0390_0007 Check (FRI_AVL_FLG in ('Y','N')),
Constraint CK007_M0390_0007 Check (SUN_AVL_FLG in ('Y','N')),
Constraint CK008_M0390_0007 Check (ACT_FLG in ('A','I','D'))
); 
