CREATE PROCEDURE Day_Clinic_Mst_Modify(
	@HOS_CD nvarchar ,
	@DAY_CLINIC_CD nvarchar ,
	@DAY_CLINIC_NM nvarchar,
	@DAY_CLINIC_TYP_CD nvarchar,
	@UNIT_DEPD_FLG nvarchar = 'N',
	@MON_FLG nvarchar = 'N' ,	
	@TUE_FLG nvarchar(1) = 'N',
	@WED_FLG nvarchar = 'N' ,
	@THU_FLG nvarchar = 'N' ,
	@FRI_FLG nvarchar = 'N' ,
	@SAT_FLG nvarchar = 'N' ,	
	@SUN_FLG nvarchar = 'N' ,	
	@MON_FR_TM nvarchar,	
	@MON_TO_TM nvarchar,	
	@TUE_FR_TM nvarchar,	
	@TUE_TO_TM nvarchar,
	@WED_FR_TM nvarchar,	
	@WED_TO_TM nvarchar,	
	@THU_FR_TM nvarchar,
	@THU_TO_TM nvarchar,	
	@FRI_FR_TM nvarchar,
	@FRI_TO_TM nvarchar,	
	@SAT_FR_TM nvarchar,
	@SAT_TO_TM nvarchar,	
	@SUN_FR_TM nvarchar,	
	@SUN_TO_TM nvarchar,	
	@MON_VENUE_NM nvarchar,	
	@TUE_VENUE_NM nvarchar,	
	@WED_VENUE_NM nvarchar,		
	@THU_VENUE_NM nvarchar,	
	@FRI_VENUE_NM nvarchar,	
	@SAT_VENUE_NM nvarchar,	
	@SUN_VENUE_NM nvarchar,	
	@PH_ANC_FLG char = 'N',	
	@PH_DLV_FLG char = 'N',
	@PH_PNC_FLG char = 'N',
	@PH_VAC_FLG char = 'N',
	@PH_RNTCP_FLG char = 'N',	
	@PH_NLEP_FLG char = 'N',
	@BASE_LVL_REF_CD nvarchar,	
	@LVL_REF_CD nvarchar ,	
	@ACTIVE_FLG char = 'Y',	
	@ENTRY_DT date ,
	@USER_CD nvarchar,
	@SESSION_ID Numeric,
	@MOD_ID nvarchar,
	@SUB_MOD_ID nvarchar,
	@ACT_FLG char = 'A',	
	@MOD_DT date,	
	@SESSION_ID_WEB nvarchar,
	@QueryType nvarchar = 'Insert')
AS
	BEGIN
		SET NOCOUNT ON;
		IF @QueryType = 'Insert'
		BEGIN 
		INSERT INTO [dbo].[DAY_CLINIC_MST]
		([HOS_CD],
		[DAY_CLINIC_CD],
		[DAY_CLINIC_NM],
		[DAY_CLINIC_TYP_CD],
		[UNIT_DEPD_FLG],
		[MON_FLG],
		[TUE_FLG],
		[WED_FLG],
		[THU_FLG],
		[FRI_FLG],
		[SAT_FLG],	
		[SUN_FLG],	
		[MON_FR_TM],	
		[MON_TO_TM],	
		[TUE_FR_TM],	
		[TUE_TO_TM],
		[WED_FR_TM],	
		[WED_TO_TM],	
		[THU_FR_TM],
		[THU_TO_TM],	
		[FRI_FR_TM],
		[FRI_TO_TM],	
		[SAT_FR_TM],
		[SAT_TO_TM],	
		[SUN_FR_TM],	
		[SUN_TO_TM,	
		[MON_VENUE_NM],	
		[TUE_VENUE_NM],	
		[WED_VENUE_NM],		
		[THU_VENUE_NM],	
		[FRI_VENUE_NM],	
		[SAT_VENUE_NM],	
		[SUN_VENUE_NM],	
		[PH_ANC_FLG],	
		[PH_DLV_FLG],
		[PH_PNC_FLG],
		[PH_VAC_FLG],
		[PH_RNTCP_FLG],	
		[PH_NLEP_FLG],
		[BASE_LVL_REF_CD],	
		[LVL_REF_CD],	
		[ACTIVE_FLG],	
		[ENTRY_DT],
		[USER_CD],
		[SESSION_ID],
		[MOD_ID],
		[SUB_MOD_ID],
		[ACT_FLG],	
		[MOD_DT],	
		[SESSION_ID_WEB]
		)
		VALUES
		  (@HOS_CD ,
		@DAY_CLINIC_CD ,
		@DAY_CLINIC_NM,
		@DAY_CLINIC_TYP_CD,
		@UNIT_DEPD_FLG,
		@MON_FLG,	
		@TUE_FLG,
		@WED_FLG,
		@THU_FLG,
		@FRI_FLG,
		@SAT_FLG,	
		@SUN_FLG,	
		@MON_FR_TM,	
		@MON_TO_TM,	
		@TUE_FR_TM,	
		@TUE_TO_TM,
		@WED_FR_TM,	
		@WED_TO_TM,	
		@THU_FR_TM,
		@THU_TO_TM,	
		@FRI_FR_TM,
		@FRI_TO_TM,	
		@SAT_FR_TM,
		@SAT_TO_TM,	
		@SUN_FR_TM,	
		@SUN_TO_TM,	
		@MON_VENUE_NM,	
		@TUE_VENUE_NM,	
		@WED_VENUE_NM,		
		@THU_VENUE_NM,	
		@FRI_VENUE_NM,	
		@SAT_VENUE_NM,	
		@SUN_VENUE_NM,	
		@PH_ANC_FLG,	
		@PH_DLV_FLG,
		@PH_PNC_FLG,
		@PH_VAC_FLG,
		@PH_RNTCP_FLG,	
		@PH_NLEP_FLG,
		@BASE_LVL_REF_CD,	
		@LVL_REF_CD,	
		@ACTIVE_FLG,	
		@ENTRY_DT ,
		@USER_CD,
		@SESSION_ID,
		@MOD_ID,
		@SUB_MOD_ID,
		@ACT_FLG,	
		@MOD_DT,	
		@SESSION_ID_WEB
		 );
	  IF @@ROWCOUNT = 1
		RETURN 1;
	  ELSE
		RETURN 0;
	END

	ELSE IF @QueryType = 'Update'
		BEGIN 
			UPDATE DAY_CLINIC_MST
				SET 
				[DAY_CLINIC_NM] = @DAY_CLINIC_NM,
				[DAY_CLINIC_TYP_CD] = @DAY_CLINIC_TYP_CD,
				[UNIT_DEPD_FLG] = @UNIT_DEPD_FLG,
				[MON_FLG] = @MON_FLG,
				[TUE_FLG] = @TUE_FLG,
				[WED_FLG] = @WED_FLG,
				[THU_FLG] = @THU_FLG,
				[FRI_FLG] = @FRI_FLG,
				[SAT_FLG] = @SAT_FLG,
				[SUN_FLG] = @SUN_FLG,
				[MON_FR_TM] = @MON_FR_TM,
				[MON_TO_TM] = @TUE_FR_TM,
				[TUE_FR_TM] = @TUE_FR_TM,	
				[TUE_TO_TM] = @TUE_TO_TM,
				[WED_FR_TM] = @WED_FR_TM,
				[WED_TO_TM] = @WED_TO_TM,
				[THU_FR_TM] = @THU_FR_TM,
				[THU_TO_TM] = @THU_TO_TM,	
				[FRI_FR_TM] = @FRI_FR_TM,
				[FRI_TO_TM] = @FRI_TO_TM,
				[SAT_FR_TM] = @SAT_FR_TM,
				[SAT_TO_TM] = @SAT_TO_TM,
				[SUN_FR_TM] = @SUN_FR_TM,
				[SUN_TO_TM] = @SUN_TO_TM,
				[MON_VENUE_NM] = @MON_VENUE_NM,
				[TUE_VENUE_NM] = @TUE_VENUE_NM,
				[WED_VENUE_NM] = @WED_VENUE_NM,
				[THU_VENUE_NM] = @THU_VENUE_NM,
				[FRI_VENUE_NM] = @FRI_VENUE_NM,
				[SAT_VENUE_NM] = @SAT_VENUE_NM,
				[SUN_VENUE_NM] = @SUN_VENUE_NM,
				[PH_ANC_FLG] = @PH_ANC_FLG,
				[PH_DLV_FLG] = @PH_DLV_FLG,
				[PH_PNC_FLG] = @PH_PNC_FLG,
				[PH_VAC_FLG] = @PH_VAC_FLG,
				[PH_RNTCP_FLG] = @PH_RNTCP_FLG,	
				[PH_NLEP_FLG] = @PH_NLEP_FLG,
				[BASE_LVL_REF_CD] =@BASE_LVL_REF_CD,	
				[LVL_REF_CD] = @LVL_REF_CD,	
				[ACTIVE_FLG] = @ACTIVE_FLG,
				[ENTRY_DT] = @ENTRY_DT,
				[USER_CD] = @USER_CD,
				[SESSION_ID] = @SESSION_ID,
				[MOD_ID] = @MOD_ID,
				[SUB_MOD_ID] = @SUB_MOD_ID,
				[ACT_FLG] = @ACT_FLG,	
				[MOD_DT] = @MOD_DT,	
				[SESSION_ID_WEB] = @SESSION_ID_WEB
				WHERE [HOS_CD] = @HOS_CD AND [DAY_CLINIC_CD] = @DAY_CLINIC_CD;
			END

	ELSE IF @QueryType = 'Delete'
		BEGIN
		DELETE FROM [dbo].[DAY_DOC_SPL]
			WHERE [HOS_CD] = @HOS_CD AND [DAY_CLINIC_CD] = @DAY_CLINIC_CD;
	END
END
